name: CI

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      working-directory: packages/windowed-observable

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.working-directory}}
        env:
          CI: true

      - name: Lint
        run: yarn lint
        working-directory: ${{env.working-directory}}
        env:
          CI: true

      - name: Test
        run: yarn test:ci
        working-directory: ${{env.working-directory}}
        env:
          CI: true

      - name: Build
        run: yarn build
        working-directory: ${{env.working-directory}}
        env:
          CI: true
