name: CI

on:
  push:
    branches:
    - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installation
      run: yarn
    - name: Testing
      run: yarn test
    - name: Linting
      run: yarn test
    - name: Build
      run: yarn build

    - name: NPM Publish
      uses: JS-DevTools/npm-publish@v1
      
